### ISSUE TITLE
No elegant way to exit the interface

### ISSUE THREAD

**Issue by kaichogami** [kaichogami/command_line_parser#2]
To exit, I have to press `ctrl + z` everytime. 
Write a method to exit it if user passes types `exit` or `bye` or anything similar.

**Comment by ashutoshdas96** [comment]
Tried of using sys.exit()

**Comment by ashutoshdas96** [comment]
else 
os._exit(0)

**Comment by kaichogami** [comment]
@ashutoshdas96 Next time, please try using referencing the issue to your pull request!  :)

**Comment by kaichogami** [comment]
Closed in pull request #3
